services:
  node:
    build:
      context: .
      target: node_base
    container_name: nightwatch_node
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - selenium
    networks:
      - nightwatch-net
    stdin_open: true
    tty: true
    env_file:
      - .env

  selenium:
    image: selenium/standalone-chrome
    container_name: nightwatch_selenium
    networks:
      - nightwatch-net
    ports:
      - "4444:4444"

networks:
  nightwatch-net:
    driver: bridge