services:
  node:
    build:
      context: .
      target: node_base
    container_name: nightwatch_node
    environment:
      NIGHTWATCH_OUTPUT: var/nightwatch
      WEBDRIVER_HOSTNAME: selenium
      WEBDRIVER_PORT: 4444
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - selenium
    networks:
      - nightwatch-net
    working_dir: /usr/src/app
    stdin_open: true
    tty: true

  selenium:
    image: selenium/standalone-chrome
    container_name: nightwatch_selenium
    networks:
      - nightwatch-net
    ports:
      - "4444:4444"

networks:
  nightwatch-net:
    driver: bridge