name: Run tests

on:
  push:
    branches:
      - main
    paths:
      - 'tests/**'
      - '.github/workflows/test.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.actor }}/node-selenium:latest
      env:
        NIGHTWATCH_OUTPUT: var/nightwatch
        WEBDRIVER_HOSTNAME: selenium
        WEBDRIVER_PORT: 4444

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: npm ci

      - name: Run tests
        run: npm run test:nightwatch:report

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: var/nightwatch

      - name: Publish Junit Report
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: '**/var/nightwatch/reports/*.xml'