name: Run tests

on:
  push:
    branches:
      - main
    paths:
      - 'tests/**'
      - '.github/workflows/test.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: node-selenium

jobs:
  test:
    runs-on: ubuntu-latest
    container: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME}}:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: npm ci

      - name: Run tests
        run: npm run test:nightwatch:report

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: var/nightwatch

      - name: Publish Junit Report
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: '**/var/nightwatch/reports/*.xml'